- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault-internal.donthi123.online:8200 validate_certs=False')}}"
  tasks:
    - name: Create a file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "username: {{ ssh | community.general.json_query('user') }}"
        create: yes
#