- name: Get secrets
  hosts: localhost
  tasks:
    - name: Create a file
      ansible.builtin.lineinfile:
        path: /tmp/test
        line: "username: {{lookup('hashi_vault', 'secret=common/data/ssh token={{vault_token}} url=https://vault.donthi123.online:8200 validate_certs=False')}}"
        create: yes
#