- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: copy Expense Nginx configuration
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: clean the old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract app content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/expense-frontend-v2.zip
    dest: /usr/share/nginx/html
    remote_src: yes


- name: start nginx
  ansible.builtin.service:
    state: restarted
    name: nginx
    enabled: yes
