- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: copy Expense Nginx configuration
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import App Pre Requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-pre-req

- name: start nginx
  ansible.builtin.service:
    state: restarted
    name: nginx
    enabled: yes
