- name: set prompt with component
  ansible.builtin.shell: set-prompt {{ component }}-{{ env }}

- name: Install Logstash
  ansible.builtin.import_role:
    name: logstash

- name: Rsyslog Configuration
  ansible.builtin.import_role:
    name: rsyslog
  when: rsyslog_config_needed